# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebaseStorageIslemleri' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'SDWebImage/WebP'
  # Pods for firebaseStorageIslemleri

  target 'firebaseStorageIslemleriTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firebaseStorageIslemleriUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
